Sub/test demo
ryoma1113/catchup-front pull request #15
Opened 2024-04-09 08:19 UTC by fujimura1013

2024-04-12 09:15 UTC, KenyaMasuko commented on packages/ui/src/components/Test/Test.test.tsx
> +import { expect, test } from "vitest";
```suggestion

```
`vitest.config.ts`でglobalsをtrueにしてあるのでここは不要かと思います！
import文削除するとeslintのwarningが出ると思うので`.eslintrc`に
```ts
env: {
 jest: true
}
```
の記述を追加してあげれば良いかと思います！

2024-04-12 09:18 UTC, KenyaMasuko commented on packages/ui/src/components/Test/Test.test.tsx
> +import { expect, test } from "vitest";
ESLintのenvに関する参考記事
https://zenn.dev/kimromi/articles/546923b7281dcb

2024-04-18 08:19 UTC, fujimura1013 commented on packages/ui/src/components/Test/Test.test.tsx
> +import { expect, test } from "vitest";
@KenyaMasuko 
修正しました〜！

2024-04-21 07:45 UTC, KenyaMasuko requested changes
変更されてないかもなのでもう一度確認お願いします！

2024-04-21 07:45 UTC, KenyaMasuko commented on packages/ui/src/components/Test/Test.test.tsx
> +import { expect, test } from "vitest";
@fujimura1013 
変更pushしてない？

2024-04-22 01:54 UTC, fujimura1013 commented on packages/ui/src/components/Test/Test.test.tsx
> +import { expect, test } from "vitest";
@KenyaMasuko 
これ修正コミットなんだけど、あってる？？
[4b2ee2e](https://github.com/peeek-develop-training/catchup-front/pull/15/commits/4b2ee2e8c65021299ce61fd0497d7c4a2c394d41)

2024-04-22 02:29 UTC, KenyaMasuko commented on packages/ui/src/components/Test/Test.test.tsx
> +import { expect, test } from "vitest";
@fujimura1013 
あってます！ありがとうございます！

2024-04-22 02:30 UTC, KenyaMasuko approved these changes

2024-04-22 02:57 UTC, merged