create todo page
ryoma1113/catchup-front pull request #4
Opened 2024-03-31 13:03 UTC by fujimura1013

2024-03-31 13:06 UTC, KenyaMasuko commented
あごめん #3 マージしちゃったからマージ先のディレクトリ変えるわ

2024-03-31 13:06 UTC, KenyaMasuko commented
やっぱなんでもなかったｗ

2024-03-31 14:40 UTC, KenyaMasuko requested changes
確認お願いしまーす！

2024-03-31 14:40 UTC, KenyaMasuko commented on apps/todo/app/page.tsx
> +  };
こうしちゃえば`SubmitHandler`型はimportしなくで済みます
```suggestion
  const onSubmit = handleSubmit((data) => {
    setTodoList(() => [...todoList, { id: todoList.length, item: data.item }]);
    reset();
  });
```

2024-03-31 14:40 UTC, KenyaMasuko commented on apps/todo/app/page.tsx
> +    setTodoList(() => [...todoList, { id: todoList.length, item: data.item }]);
idの生成は今回クライアントでやっちゃいましょうか（このPRで修正しなくておけ）
lengthでとるとuniqueにならないのでMath.randomとか使うか、タスクのコンポーネントに分ける時に`useId`使うといいと思います！
ちなみにkeyが被ると下記のエラーが発生します
![image](https://github.com/peeek-develop-training/catchup-front/assets/85816730/cc6916c9-a768-4dc2-9e05-4b8c77de5e45)

2024-03-31 14:40 UTC, KenyaMasuko commented on apps/todo/app/page.tsx
> +};
バリデーションライブラリにyupかzodを入れて欲しいです！

2024-03-31 14:40 UTC, KenyaMasuko commented on apps/todo/app/page.tsx
> +  id: number | null;
`null`の場合ってどんな時ですかね？ぱっと思いつかなかったので質問です！

2024-03-31 14:40 UTC, KenyaMasuko commented on apps/todo/app/page.tsx
> +};
こういうやつはすでに定義してある型を使うといいです
```suggestion
type Todo = {
  id: number | null;
} & Input;
```

2024-03-31 14:40 UTC, KenyaMasuko commented on apps/todo/app/page.tsx
> +  const onDelete = (id: number) => {
ここもすでに定義してある型を使用しましょうか
```suggestion
  const onDelete = (id: Todo['id']) => {
```

2024-03-31 14:40 UTC, KenyaMasuko commented on apps/todo/app/page.tsx
> +    setTodoList(() => [...todoList, { id: todoList.length, item: data.item }]);
`useState`のsetterはコールバック関数を引数にとれます。そのコールバック関数の引数（修正しているコードで言うと`prevTodoList`）は変更を加える前のステートです。ステートを更新する時には今のやりかたの更新ではバグるパターンがあります。TODOアプリケーションくらいの単純な構造では動きますが、1つのイベントハンドラの中で複数回ステートを更新するバグります。詳しくはドキュメントの[このページ](https://ja.react.dev/learn/state-as-a-snapshot)を見てみると良いかと思います。（わからなかったら聞いてね）
```suggestion
    setTodoList((prevTodoList) => [...prevTodoList, { id: prevTodoList.length, item: data.item }]);
```

2024-03-31 14:40 UTC, KenyaMasuko commented on apps/todo/app/page.tsx
> +    setTodoList(todoList.filter((todo) => todo.id !== id));
ここも`useState`の更新に関する話です！
```suggestion
    setTodoList(prev => prev.filter((todo) => todo.id !== id));
```

2024-03-31 14:40 UTC, KenyaMasuko commented on apps/todo/app/page.tsx
> +            <button onClick={() => onDelete(todo.id!)}>完了</button>
ここの`!`(Non-Null Assertion Operator)はnullの可能性があるから使用していますか？
基本的に`!`は使用しないで実装を進めてください。Null安全性が破壊されます。

2024-03-31 14:50 UTC, KenyaMasuko commented on apps/todo/app/page.tsx
> +    setTodoList(() => [...todoList, { id: todoList.length, item: data.item }]);
httpsだったらこんなのも使えるっぽい
https://developer.mozilla.org/ja/docs/Web/API/Crypto/randomUUID
ライブラリだったら[nanoid](https://github.com/ai/nanoid)とかかな

2024-04-02 08:49 UTC, fujimura1013 commented on apps/todo/app/page.tsx
> +  };
修正しました！
[36be738](https://github.com/peeek-develop-training/catchup-front/pull/4/commits/36be738f665914da60544d01e560a2475ecdde2e)

2024-04-02 08:54 UTC, fujimura1013 commented on apps/todo/app/page.tsx
> +    setTodoList(() => [...todoList, { id: todoList.length, item: data.item }]);
@KenyaMasuko 
submitしたら、`setTodoList(() => [...todoList, { id: todoList.length, item: data.item }]);`の箇所は新しくfetchしたデータが入ると思っていたので、とりあえずlengthでidつけちゃってました、、！
了解です！

2024-04-02 08:55 UTC, fujimura1013 commented on apps/todo/app/page.tsx
> +};
yup使いました！
[c838afc](https://github.com/peeek-develop-training/catchup-front/pull/4/commits/c838afc85f6f90b609e1d13b0d4b5d427604ec6a)

2024-04-02 08:58 UTC, fujimura1013 commented on apps/todo/app/page.tsx
> +  id: number | null;
@KenyaMasuko 
勝手に一括更新の想定になってました、普通に`null`いらないです！
[70813b0](https://github.com/peeek-develop-training/catchup-front/pull/4/commits/70813b00bdf3e99a850c575fe3c7d2aacc75e7ef)

2024-04-02 08:59 UTC, fujimura1013 commented on apps/todo/app/page.tsx
> +};
修正しました
[10069f4](https://github.com/peeek-develop-training/catchup-front/pull/4/commits/10069f43b26d9141792bda5733522d988246a5dd)

2024-04-02 08:59 UTC, fujimura1013 commented on apps/todo/app/page.tsx
> +  const onDelete = (id: number) => {
修正しました
[121cf0d](https://github.com/peeek-develop-training/catchup-front/pull/4/commits/121cf0df65cb4106b0d727864c8d19dccba01862)

2024-04-02 09:00 UTC, fujimura1013 commented on apps/todo/app/page.tsx
> +    setTodoList(() => [...todoList, { id: todoList.length, item: data.item }]);
あってますかね？？
[9772ea1](https://github.com/peeek-develop-training/catchup-front/pull/4/commits/9772ea16ac92a03cadd573545f6c88ca831f5d32)

2024-04-02 09:01 UTC, fujimura1013 commented on apps/todo/app/page.tsx
> +    setTodoList(todoList.filter((todo) => todo.id !== id));
同じく修正しました！
[a132069](https://github.com/peeek-develop-training/catchup-front/pull/4/commits/a132069d76746fa3f5c1cc3e0d19d782d1982bbc)

2024-04-02 09:01 UTC, fujimura1013 commented on apps/todo/app/page.tsx
> +            <button onClick={() => onDelete(todo.id!)}>完了</button>
`null`不要なのでこちらも削除しました！
[70813b0](https://github.com/peeek-develop-training/catchup-front/pull/4/commits/70813b00bdf3e99a850c575fe3c7d2aacc75e7ef)

2024-04-02 09:40 UTC, KenyaMasuko commented on apps/todo/app/page.tsx
> +    setTodoList(() => [...todoList, { id: todoList.length, item: data.item }]);
あっています！
なんでこう修正したのか他の人が見ても分かるように記載して欲しいです！

2024-04-02 10:23 UTC, KenyaMasuko requested changes
コメント確認おなしゃす

2024-04-03 03:07 UTC, fujimura1013 commented on apps/todo/app/page.tsx
> +    setTodoList(() => [...todoList, { id: todoList.length, item: data.item }]);
参考：https://ja.react.dev/reference/react/useState#updating-state-based-on-the-previous-state

`setTodoList(() => [...todoList, { id: todoList.length, item: data.item }]);`だと直前の`todoList`を更新できない
↓
`setTodoList((prev) => [...prev, { id: prev.length, item: data.item }]);`更新用関数：`prev`を呼び出す

2024-04-03 03:10 UTC, KenyaMasuko approved these changes
Thanks!

2024-04-03 03:13 UTC, merged

2024-04-03 06:36 UTC, KenyaMasuko commented on apps/todo/app/page.tsx
> +    setTodoList(() => [...todoList, { id: todoList.length, item: data.item }]);
なぜkeyはuniqueでなければいけないのか
https://ja.react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key