create todo item page
ryoma1113/catchup-front pull request #5
Opened 2024-03-31 13:40 UTC by fujimura1013

2024-03-31 15:06 UTC, KenyaMasuko requested changes
#4  で指摘したようなこともこのPRであると思うので、一旦指摘はしないでおきますー！

2024-03-31 15:06 UTC, KenyaMasuko commented on apps/todo/app/(item)/[id]/page.tsx
ディレクトリですが
`app/[id]/page.tsx`でもいけないですかね？

2024-04-02 10:21 UTC, fujimura1013 commented on apps/todo/app/(item)/[id]/page.tsx
ディレクトリ変更と重複レビュー修正しました！

2024-04-02 14:21 UTC, KenyaMasuko approved these changes
ないす〜

2024-04-03 03:13 UTC, merged